app:
  github:
    token: ${GITHUB_TOKEN} # env variable
    api-url: "https://api.github.com"
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}
    api-url: "https://api.stackexchange.com/2.3/"
  base-url: http://localhost:8080
  scheduler:
    interval-in-ms: 120000
spring:
  application:
    name: Scrapper
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
